version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
      time: "21:00"
    open-pull-requests-limit: 10
    target-branch: master
    registries:
      - maven-central
      - maven-google
      - gralde-plugin

registries:
  maven-central:
    type: maven-central
    url: "https://repo.maven.apache.org/maven2/"
  maven-google:
    type: maven-repository
    url: "https://dl.google.com/dl/android/maven2/"
  gralde-plugin:
    type: maven-repository
    url: "https://plugins.gradle.org/m2/"