package com.imcys.bilias.feature.merge.ass.model

fun buildScriptInfo(title: String, width: Int, height: Int): String {
    return ScriptInfo(title, width, height).toString()
}

private data class ScriptInfo(
    private val title: String,
    private val width: Int,
    private val height: Int
) {
    override fun toString(): String {
        return """
[Script Info]
; Script generated by BILIBILIAS Danmaku Converter
Title: $title
ScriptType: v4.00+
PlayResX: $width
PlayResY: $height
ScaledBorderAndShadow: no
"""
    }

}